services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1001:1001
    group_add:
      - 105
    volumes:
      - /home/media/.config/jellyfin:/config
      - /home/media/.cache/jellyfin:/cache
      - type: bind
        source: /mnt/media
        target: /media
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
    ports:
      - 8096:8096
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Canada/Eastern
    volumes:
      - /home/media/.config/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Canada/Eastern
    volumes:
      - /home/media/.config/radarr:/config
      - /mnt/media/Movies:/movies
      - /mnt/media/Downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Canada/Eastern
    volumes:
      - /home/media/.config/sonarr:/config
      - /mnt/media/Shows:/tv
      - /mnt/media/Downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Canada/Eastern
    volumes:
      - /home/media/.config/bazarr:/config
      - /mnt/media/Movies:/movies
      - /mnt/media/Shows:/tv
    ports:
      - 6767:6767
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    ports:
      - 8191:8191
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Canada/Eastern
    ports:
      - 5055:5055
    volumes:
      - /home/media/.config/jellyseerr:/app/config
    restart: unless-stopped

  glances:
    image: nicolargo/glances:latest
    container_name: glances
    secrets:
      - source: glances_password
        target: /root/.config/glances/glances.pwd
    ports:
      - 61208:61208
    pid: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/os-release:/etc/os-release:ro
    environment:
      - "GLANCES_OPT=-w --password"
    restart: unless-stopped

  caddy:
    image: caddy:latest
    container_name: caddy
    cap_add:
      - NET_ADMIN
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - /home/media/.config/caddy/Caddyfile:/etc/caddy/Caddyfile
    restart: unless-stopped

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    network_mode: "service:gluetun"
    secrets:
      - transmission_user
      - transmission_pass
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Etc/UTC
      - FILE__USER=/run/secrets/transmission_user
      - FILE__PASS=/run/secrets/transmission_pass
    volumes:
      - /home/media/.config/transmission:/config
      - /mnt/media/Downloads:/downloads
    restart: unless-stopped

  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp
      - 8388:8388/tcp
      - 8388:8388/udp
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    volumes:
      - /home/media/.config/gluetun:/gluetun
    secrets:
      - openvpn_user
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=openvpn
      - OPENVPN_USER_SECRETFILE=/run/secrets/openvpn_user
      - TZ=Canada/Eastern
      - UPDATER_PERIOD=24h
      - SERVER_COUNTRIES=Canada,Netherlands,Sweden,Switzerland
    restart: unless-stopped

  netdata:
    image: netdata/netdata
    container_name: netdata
    pid: host
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    ports:
      - 19999:19999
    volumes:
      - netdataconfig:/etc/netdata
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /etc/localtime:/etc/localtime:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /var/log:/host/var/log:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  caddy_data:
  caddy_config:
  netdataconfig:
  netdatalib:
  netdatacache:

secrets:
  transmission_user:
    file: ./secrets/transmission_user
  transmission_pass:
    file: ./secrets/transmission_pass
  glances_password:
    file: ./secrets/glances_password
  openvpn_user:
    file: ./secrets/openvpn_user
